/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenus.configuracionesAdmin;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelos.objetos.Usuario;

import modelos.database.UsuarioDb;

/**
 *
 * @author sergio
 */
public class Usuarios extends javax.swing.JFrame {

    private ArrayList<Usuario> usuario;
    UsuarioDb usuarioDb;

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
         usuarioDb= new UsuarioDb();
        
        agregarUsuarios();
    }

    private void agregarUsuarios() {
        btnAscender.setEnabled(false);
                btnDescender.setEnabled(false);
                btnEliminar.setEnabled(false);
        usuario = usuarioDb.leerUsuariosArray();
        DefaultTableModel tb = (DefaultTableModel) tabla.getModel();
        int rowCount = tb.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
    tb.removeRow(i);
}
        for (int i = 0; i < usuario.size(); i++) {
            String role;
            switch (usuario.get(i).getRol()) {
                case 2:
                    role="Admin";
                    break;
                case 1:
                    role="Estudiante";
                    break;
                default:
                    role="Lector";
                    break;
            }
            tb.addRow(new Object[]{usuario.get(i).getUsername(), usuario.get(i).getEmail(), usuario.get(i).getNombre(),
                usuario.get(i).getApellido(), usuario.get(i).getNumeroTel(),role});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnAscender = new javax.swing.JButton();
        btnDescender = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jLabel1.setText("Usuarios");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Email", "Nombre", "Apellido", "Telefono", "Role"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tablaComponentMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(4).setPreferredWidth(60);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        btnAscender.setText("Ascender");
        btnAscender.setEnabled(false);
        btnAscender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAscenderActionPerformed(evt);
            }
        });

        btnDescender.setText("Descender");
        btnDescender.setEnabled(false);
        btnDescender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescenderActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(java.awt.Color.red);
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.setOpaque(true);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(240, 240, 240))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDescender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAscender)
                                .addGap(24, 24, 24))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAscender)
                    .addComponent(btnDescender)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tablaComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaComponentMoved

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        if (tabla.getSelectedRow()>0) {
            if (usuario.get(tabla.getSelectedRow()).getRol()!=2) {
                if (usuario.get(tabla.getSelectedRow()).getRol()==1) {
                    btnAscender.setEnabled(true);
                }
                if (usuario.get(tabla.getSelectedRow()).getRol()==3) {
                    btnDescender.setEnabled(true);
                }
                btnEliminar.setEnabled(true);
            }else{
                btnAscender.setEnabled(false);
                btnDescender.setEnabled(false);
                btnEliminar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void btnAscenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAscenderActionPerformed
        usuarioDb.ascenderUsuario(usuario.get(tabla.getSelectedRow()), true);
        agregarUsuarios();
    }//GEN-LAST:event_btnAscenderActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        usuarioDb.eliminarUsuario(usuario.get(tabla.getSelectedRow()));
        agregarUsuarios();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDescenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescenderActionPerformed
        usuarioDb.ascenderUsuario(usuario.get(tabla.getSelectedRow()), false);
        agregarUsuarios();
    }//GEN-LAST:event_btnDescenderActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAscender;
    private javax.swing.JButton btnDescender;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
