/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenus.lineaDeTiempo;

import api.login.Login;
import static api.login.Login.usuarioB;
import static api.login.Login.usuarioLogueado;
import java.util.List;
import javax.swing.JOptionPane;
import modelos.database.HechoHistoricoDb;
import modelos.database.PeriodoDb;
import modelos.objetos.HechoHistorico;
import modelos.objetos.Periodo;

/**
 *
 * @author sergio
 */
public class EventoDeTiempo extends javax.swing.JPanel {

    private final HechoHistorico hechoHistorico;

    /**
     * Creates new form EventoDeTiempo
     *
     * @param hechoHistorico
     */
    public EventoDeTiempo(HechoHistorico hechoHistorico) {
        initComponents();
        this.hechoHistorico = hechoHistorico;
        if (hechoHistorico != null) {
            System.out.println("titulo " + hechoHistorico.getTitulo());
            lblTitulo.setText(hechoHistorico.getTitulo());
            lblDescripcion.setText(hechoHistorico.getDescripcion());
            calendarFechaInicio.setText(hechoHistorico.getFechaInicio());
            calendarioFechaFin.setText(hechoHistorico.getFechaFin());
            /*Cargar los periodos de la base de datos*/
            //mostramos eventos
            PeriodoDb p = new PeriodoDb();
            List<Periodo> listaP = p.getPeriodo();
            for (int i = 0; i < listaP.size(); i++) {
                Periodo periodoM = listaP.get(i);
                periodos.addItem(periodoM.getNombre());
            }

            autor.setText(hechoHistorico.getAutor());
            acI.setText(hechoHistorico.getAcI());
            acF.setText(hechoHistorico.getAcF());

        }
        this.setSize(1030, 445);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDescripcion = new javax.swing.JTextArea();
        calendarFechaInicio = new javax.swing.JTextField();
        calendarioFechaFin = new javax.swing.JTextField();
        periodos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        acI = new javax.swing.JTextField();
        acF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setAutoscrolls(true);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1032, 450));

        lblTitulo.setBackground(new java.awt.Color(218, 218, 255));
        lblTitulo.setFont(new java.awt.Font("Noto Sans CJK KR Light", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 204));
        lblTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTituloActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha Inicio*");

        jLabel2.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Fin");

        lblDescripcion.setBackground(new java.awt.Color(229, 229, 255));
        lblDescripcion.setColumns(20);
        lblDescripcion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDescripcion.setLineWrap(true);
        lblDescripcion.setRows(5);
        lblDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(lblDescripcion);

        calendarFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarFechaInicioActionPerformed(evt);
            }
        });

        calendarioFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioFechaFinActionPerformed(evt);
            }
        });

        periodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Epoca*");

        jLabel4.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Autor");

        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Acontecimiento Inicial*");

        jLabel6.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Acontecimiento Final");

        acI.setText("a.c");
        acI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acIActionPerformed(evt);
            }
        });

        acF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acFActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Solo 3 caracteres para el acontecimeinto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calendarFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calendarioFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(periodos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(acI, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acF, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(calendarFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(periodos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(calendarioFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(acI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void lblTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloActionPerformed

    private void calendarFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarFechaInicioActionPerformed

    private void calendarioFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioFechaFinActionPerformed

    private void periodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodosActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorActionPerformed

    private void acIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acIActionPerformed

    private void acFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acFActionPerformed
    public HechoHistorico devolverHH() {
        return this.hechoHistorico;
    }

    public HechoHistorico hechoHistoricoNuevo() {
        HechoHistorico edt = null;
        if (calendarFechaInicio.getText().isEmpty()
                || lblDescripcion.getText().isEmpty() || lblTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            String t = lblTitulo.getText();
            String d = lblDescripcion.getText();
            String dateInit = calendarFechaInicio.getText();
            String dateFin = calendarioFechaFin.getText();

            //HechoHistoricoDb hechoHistoricoDb = new HechoHistoricoDb();
            //procedemos a crear el hecho historico
            String periodo = (String) periodos.getSelectedItem();
            String autorH = autor.getText();
            String Aci = acI.getText();
            String Acf = acF.getText();

            if (periodo.equals("")) {
                periodo = "sin periodo";
            } else if (autorH.equals("")) {
                if (usuarioLogueado == null) {
                    if (usuarioB == null) {
                    } else {
                        autorH = usuarioB.getUsername();
                        System.out.println(usuarioB.getUsername());
                    }
                } else {
                    autorH = usuarioLogueado.getUsername();
                    System.out.println(usuarioLogueado.getUsername());
                }
            } else if (Aci.equals("")) {
                Aci = "a.C";
            } else if (Acf.equals("")) {
                Acf = "-";
            }

            edt = new HechoHistorico(this.hechoHistorico.getId(), t, autorH, periodo, htmlC, dateInit, dateFin, Aci, Acf, categoria, d);
        }
        return edt;
    }

    public static String htmlC = "-";
    public static String categoria = "Escritura1";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acF;
    private javax.swing.JTextField acI;
    private javax.swing.JTextField autor;
    private javax.swing.JTextField calendarFechaInicio;
    private javax.swing.JTextField calendarioFechaFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDescripcion;
    private javax.swing.JTextField lblTitulo;
    private javax.swing.JComboBox<String> periodos;
    // End of variables declaration//GEN-END:variables
}
