/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenus.calendarioCholquij;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelos.database.Mensaje;
import modelos.database.informacionCalendarioCholqijDb;
import modelos.objetos.Informacion2;
import modelos.objetos.Usuario;
import modelos.objetos.datoCalendarioCholqij;

/**
 *
 * @author Esmeralda
 */
public class panelInformacionCalendarioCholqij extends javax.swing.JPanel {

    /**
     * Creates new form panelInformacionCalendarioCholqij
     */
    private int opcionInfo = 0;
    private final Usuario usuarioLogueado;
    private datoCalendarioCholqij datoCC;
    private final informacionCalendarioCholqijDb infCC = new informacionCalendarioCholqijDb();
    private final Mensaje mensajes = new Mensaje();

    public panelInformacionCalendarioCholqij(int opcion, Usuario user) {
        initComponents();
        //fondo de pantalla
        Imagen img = new Imagen();
        this.add(img);
        this.repaint();
        panelTitulo.setBackground(new Color(255,255,255,100));
        opcionInfo = opcion;
        usuarioLogueado = user;
        //dependiendo del rol se puede editar o no.


        /*
        validacionusuario();
*/
        
        
        
        areaInformacion.setLineWrap(true);
        //dependiendo la opcion leemos la DB
        clasificarDatoMostrar();
    }

    private void validacionusuario() {
        int rolU = usuarioLogueado.getRol();
        if (rolU == 1) {//es admin
            areaInformacion.setEditable(true);
            btnEditar.setVisible(true);
        } else {//es invitado
            areaInformacion.setEditable(false);
            btnEditar.setVisible(false);
        }
    }

    ;


    private void clasificarDatoMostrar() {
        Informacion2 datoLee = infCC.leerDatoCalendarioCholqij(opcionInfo);
        lblTitulo.setText(datoLee.getNombre());
        areaInformacion.setText(datoLee.getDescEscritorio());

      //  ImageIcon imIconExit = new ImageIcon(datoLee.getUrlImagen());
       // Icon iconoExit = new ImageIcon(imIconExit.getImage().getScaledInstance(250, 250, Image.SCALE_DEFAULT));
        //iconoCalendario.setIcon(iconoExit);

       // datoCC = datoLee;
    }

    public class Imagen extends javax.swing.JPanel {

        ImageIcon BG = new ImageIcon("src/submenus/perfilUsuario/imagenesPerfilUsuario/fondoPerfil.jpg");

        public Imagen() {
            this.setSize(1300, 650);
        }

        @Override
        public void paint(Graphics grafico) {
            Dimension height = getSize();

            grafico.drawImage(BG.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        iconoCalendario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaInformacion = new javax.swing.JTextArea();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1100, 550));

        lblTitulo.setFont(new java.awt.Font("Jenna Sue", 3, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 0, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText(" ");

        btnEditar.setBackground(new java.awt.Color(255, 255, 204));
        btnEditar.setFont(new java.awt.Font("Lobster", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        areaInformacion.setEditable(false);
        areaInformacion.setBackground(new java.awt.Color(255, 255, 204));
        areaInformacion.setColumns(20);
        areaInformacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        areaInformacion.setLineWrap(true);
        areaInformacion.setRows(5);
        areaInformacion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(areaInformacion);

        lblTitulo2.setFont(new java.awt.Font("Jenna Sue", 1, 48)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(43, 145, 113));
        lblTitulo2.setText("CALENDARIO CHOLQIJ");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo2)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(iconoCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconoCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //validar que no este vacio el concepto
        if (areaInformacion.getText().isEmpty()) { //caja de texto vacia
            mensajes.error("Debe ingresar informacion acerca de " + datoCC.getTitulo());
        } else {//caja de texto con info
            String concepto = areaInformacion.getText();
            //editamos el dato.
            datoCalendarioCholqij datoUpdate = new datoCalendarioCholqij(datoCC.getId(), datoCC.getTitulo(), concepto, datoCC.getUrlImagen());
            infCC.actualizarDatoCalendarioCholqij(datoCC);
        }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaInformacion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel iconoCalendario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
