/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenus.calendarioCholquij;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import principal.backend.calendari_cholquij.matriz.ManejadorDeCalendarioCholqij;
import principal.backend.calendari_cholquij.matriz.elementos.KinCholqij;

/**
 *
 * @author Esmeralda
 */
public class panelNahualEnergiaCholqij extends javax.swing.JPanel {

    /**
     * Creates new form panelNahualEnergiaCholqij
     */
    private ManejadorDeCalendarioCholqij manejador;

    public panelNahualEnergiaCholqij() {
        initComponents();
        this.manejador = new ManejadorDeCalendarioCholqij();

        this.infoTextArea.setText(contarTexto(""
                + "Imox significa la esencia de nuestra conciencia\n "
                + "y de nuestra mente. Imox es el lado izquierdo, la \n"
                + "parte sutil del ser humano. Imox es la sensibilidad,\n"
                + "lo inusual y lo excéntrico."));

        infoTextArea.setEditable(false);
        //fondo de pantalla
        Imagen img = new Imagen();
        jPanel1.add(img);
        jPanel1.repaint();

    }

    public class Imagen extends javax.swing.JPanel {

        ImageIcon BG = new ImageIcon("src/submenus/perfilUsuario/imagenesPerfilUsuario/fondoPerfil.jpg");

        public Imagen() {
            this.setSize(1300, 650);
        }

        @Override
        public void paint(Graphics grafico) {
            Dimension height = getSize();

            grafico.drawImage(BG.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        energiaLabel = new javax.swing.JLabel();
        anteriorButton = new javax.swing.JButton();
        siguienteButton = new javax.swing.JButton();
        nahualLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        energiaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenesNumerosMayas/numero1.jpg"))); // NOI18N

        anteriorButton.setBackground(new java.awt.Color(255, 255, 204));
        anteriorButton.setFont(new java.awt.Font("Lobster", 1, 36)); // NOI18N
        anteriorButton.setForeground(new java.awt.Color(0, 0, 153));
        anteriorButton.setText("<-");
        anteriorButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        anteriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButtonActionPerformed(evt);
            }
        });

        siguienteButton.setBackground(new java.awt.Color(255, 255, 204));
        siguienteButton.setFont(new java.awt.Font("Lobster", 1, 36)); // NOI18N
        siguienteButton.setForeground(new java.awt.Color(0, 0, 153));
        siguienteButton.setText("->");
        siguienteButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        siguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButtonActionPerformed(evt);
            }
        });

        nahualLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenesNahualesMayas/Nahual1.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Energia");

        jLabel2.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel2.setText("Nahual");

        infoTextArea.setEditable(false);
        infoTextArea.setBackground(new java.awt.Color(253, 236, 253));
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("Lobster", 0, 24)); // NOI18N
        infoTextArea.setForeground(new java.awt.Color(0, 0, 0));
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setText(" ");
        infoTextArea.setToolTipText("");
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jenna Sue", 1, 50), new java.awt.Color(0, 153, 153))); // NOI18N
        jScrollPane1.setViewportView(infoTextArea);

        lblTitulo.setFont(new java.awt.Font("Jenna Sue", 1, 55)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 0, 102));
        lblTitulo.setText("NAHUAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel1))
                                .addComponent(nahualLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(energiaLabel)
                                .addGap(3, 3, 3)))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(anteriorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(siguienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitulo)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nahualLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(energiaLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anteriorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void anteriorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButtonActionPerformed
        KinCholqij dia = manejador.verDiaAnterior();
        cambioDeDia(dia);
    }//GEN-LAST:event_anteriorButtonActionPerformed

    private void cambioDeDia(KinCholqij dia) {
        energiaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(dia.getEnergia().getDireccionDeImagen()))); // NOI18N
        nahualLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(dia.getNahual().getDireccionDeImagen()))); // NOI18N
        infoTextArea.setText(contarTexto(dia.getNahual().getDescripcion()));
    }

    private String contarTexto(String text) {
        String retornar;
        String[] split = text.split(" ");
        if (split.length > 2) {
            retornar = split[0] + "\n\n";
            if (split[1].equalsIgnoreCase("significa")) {
                retornar += "Significa ";
            } else if (split[1].equalsIgnoreCase("simboliza")) {
                retornar += "Simboliza ";
            } else {
                retornar += split[1];
            }
            int contador = 0;
            String cadena;
            for (int i = 2; i < split.length; i++) {
                cadena = split[i].replaceAll("\n", "");
                cadena = cadena.replaceAll(" ", "");
                if (contador == 6) {
                    retornar += cadena + "\n";
                    contador = 0;
                } else {
                    retornar += cadena + " ";
                    contador++;
                }
            }
            return retornar;
        }
        return "";

    }


    private void siguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButtonActionPerformed
        KinCholqij dia = manejador.verDiaSiguiente();
        cambioDeDia(dia);
    }//GEN-LAST:event_siguienteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorButton;
    private javax.swing.JLabel energiaLabel;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel nahualLabel;
    private javax.swing.JButton siguienteButton;
    // End of variables declaration//GEN-END:variables
}
