/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenus.lineaDeTiempo;

import java.sql.Date;
import javax.swing.JOptionPane;
import modelos.database.HechoHistoricoDb;
import modelos.objetos.HechoHistorico;

/**
 *
 * @author sergio
 */
public class EventoDeTiempo extends javax.swing.JPanel {

    private final HechoHistorico hechoHistorico;

    /**
     * Creates new form EventoDeTiempo
     *
     * @param hechoHistorico
     */
    public EventoDeTiempo(HechoHistorico hechoHistorico) {
        initComponents();
        this.hechoHistorico = hechoHistorico;
        if (hechoHistorico != null) {
            System.out.println("titulo " + hechoHistorico.getTitulo());
            lblTitulo.setText(hechoHistorico.getTitulo());
            lblDescripcion.setText(hechoHistorico.getDescripcion());
            calendarFechaInicio.setDate(hechoHistorico.getFechaInicio());
            calendarioFechaFin.setDate(hechoHistorico.getFechaFinalizacion());
        }
        this.setSize(1030, 445);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JTextField();
        calendarFechaInicio = new com.toedter.calendar.JDateChooser();
        calendarioFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDescripcion = new javax.swing.JTextArea();

        setAutoscrolls(true);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1032, 450));

        lblTitulo.setBackground(new java.awt.Color(218, 218, 255));
        lblTitulo.setFont(new java.awt.Font("Noto Sans CJK KR Light", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 204));
        lblTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTituloActionPerformed(evt);
            }
        });

        calendarFechaInicio.setBackground(new java.awt.Color(229, 229, 255));
        calendarFechaInicio.setForeground(new java.awt.Color(0, 102, 204));
        calendarFechaInicio.setFont(new java.awt.Font("Lobster", 0, 14)); // NOI18N

        calendarioFechaFin.setBackground(new java.awt.Color(229, 229, 255));

        jLabel1.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha Inicio");

        jLabel2.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Fin");

        lblDescripcion.setBackground(new java.awt.Color(229, 229, 255));
        lblDescripcion.setColumns(20);
        lblDescripcion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDescripcion.setLineWrap(true);
        lblDescripcion.setRows(5);
        lblDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(lblDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(296, 296, 296))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(calendarFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(calendarioFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calendarioFechaFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void lblTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloActionPerformed
    public HechoHistorico devolverHH() {
        return this.hechoHistorico;
    }

    public HechoHistorico hechoHistoricoNuevo() {
        HechoHistorico edt = null;
        if (calendarFechaInicio.getDate() == null || calendarioFechaFin.getDate() == null
                || lblDescripcion.getText().isEmpty() || lblTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            String t = lblTitulo.getText();
            String d = lblDescripcion.getText();
            Long a = calendarFechaInicio.getDate().getTime();
            Date dateInit = new Date(a);
            Long b = calendarioFechaFin.getDate().getTime();
            Date dateF = new Date(b);

            HechoHistoricoDb hechoHistoricoDb = new HechoHistoricoDb();

            edt = new HechoHistorico(this.hechoHistorico.getId(),
                    dateInit, dateF, t, d);
        }
        return edt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calendarFechaInicio;
    private com.toedter.calendar.JDateChooser calendarioFechaFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDescripcion;
    private javax.swing.JTextField lblTitulo;
    // End of variables declaration//GEN-END:variables
}
