/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenus.ruedaCalendarica;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Esmeralda
 */
public class ruedaCalendarica extends javax.swing.JPanel {

    private boolean sobrePasaFechaPivote = false;

    /**
     * Creates new form ruedaCalendarica
     */
    public ruedaCalendarica() {
        initComponents();
        //fondo de pantalla
        Imagen img = new Imagen();
        this.add(img);
        this.repaint();

        ImageIcon imgB = new ImageIcon("src/submenus/ruedaCalendarica/imagenesCuentaLarga/baktun.png");
        Icon iconoB = new ImageIcon(imgB.getImage().getScaledInstance(115, 75, Image.SCALE_DEFAULT));
        lblBaktun.setIcon(iconoB);

        ImageIcon imgK = new ImageIcon("src/submenus/ruedaCalendarica/imagenesCuentaLarga/katun.png");
        Icon iconoK = new ImageIcon(imgK.getImage().getScaledInstance(115, 75, Image.SCALE_DEFAULT));
        lblKatun.setIcon(iconoK);

        ImageIcon imgT = new ImageIcon("src/submenus/ruedaCalendarica/imagenesCuentaLarga/tun.png");
        Icon iconoT = new ImageIcon(imgT.getImage().getScaledInstance(115, 75, Image.SCALE_DEFAULT));
        lblTun.setIcon(iconoT);

        ImageIcon imgU = new ImageIcon("src/submenus/ruedaCalendarica/imagenesCuentaLarga/uinal.png");
        Icon iconoU = new ImageIcon(imgU.getImage().getScaledInstance(115, 75, Image.SCALE_DEFAULT));
        lblUinal.setIcon(iconoU);

        ImageIcon imgKin = new ImageIcon("src/submenus/ruedaCalendarica/imagenesCuentaLarga/kin.png");
        Icon iconoKin = new ImageIcon(imgKin.getImage().getScaledInstance(115, 75, Image.SCALE_DEFAULT));
        lblKin.setIcon(iconoKin);

    }

    public class Imagen extends javax.swing.JPanel {

        ImageIcon BG = new ImageIcon("src/submenus/perfilUsuario/imagenesPerfilUsuario/fondoPerfil.jpg");

        public Imagen() {
            this.setSize(1300, 650);
        }

        @Override
        public void paint(Graphics grafico) {
            Dimension height = getSize();

            grafico.drawImage(BG.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtKatun = new javax.swing.JTextField();
        txtBaktun = new javax.swing.JTextField();
        txtTun = new javax.swing.JTextField();
        txtUinal = new javax.swing.JTextField();
        txtKin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblKatun = new javax.swing.JLabel();
        lblTun = new javax.swing.JLabel();
        lblBaktun = new javax.swing.JLabel();
        lblUinal = new javax.swing.JLabel();
        lblKin = new javax.swing.JLabel();
        diaTzol = new javax.swing.JTextField();
        diaHab = new javax.swing.JTextField();
        icH = new javax.swing.JLabel();
        icTzol = new javax.swing.JLabel();
        lblNombreT = new javax.swing.JLabel();
        lblNombeH = new javax.swing.JLabel();

        boxDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Jenna Sue", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(112, 54, 139));
        jLabel2.setText("RUEDA CALENDARICA");

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtKatun.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtKatun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKatun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Katun", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jenna Sue", 1, 24), new java.awt.Color(255, 0, 153))); // NOI18N

        txtBaktun.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBaktun.setForeground(new java.awt.Color(25, 9, 9));
        txtBaktun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBaktun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Baktun", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jenna Sue", 1, 24), new java.awt.Color(255, 0, 153))); // NOI18N
        txtBaktun.setSelectionColor(new java.awt.Color(93, 145, 250));
        txtBaktun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaktunActionPerformed(evt);
            }
        });

        txtTun.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTun.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tun", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jenna Sue", 1, 24), new java.awt.Color(255, 0, 153))); // NOI18N

        txtUinal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtUinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUinal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Uinal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jenna Sue", 1, 24), new java.awt.Color(255, 0, 153))); // NOI18N

        txtKin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtKin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jenna Sue", 1, 24), new java.awt.Color(255, 0, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 54, 139));
        jLabel1.setText("Cuenta Larga");

        lblKatun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblBaktun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblKin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        diaTzol.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        diaTzol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diaTzol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tzolqin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jenna Sue", 1, 24), new java.awt.Color(255, 0, 153))); // NOI18N

        diaHab.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        diaHab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diaHab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Haab", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jenna Sue", 1, 24), new java.awt.Color(255, 0, 153))); // NOI18N

        icH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        icTzol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNombreT.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        lblNombreT.setForeground(new java.awt.Color(255, 153, 0));
        lblNombreT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblNombeH.setFont(new java.awt.Font("Jenna Sue", 1, 36)); // NOI18N
        lblNombeH.setForeground(new java.awt.Color(255, 153, 0));
        lblNombeH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBaktun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBaktun, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblKatun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKatun, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTun, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblKin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombeH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diaHab, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(diaTzol, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(icH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(icTzol, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKatun, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTun, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBaktun, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUinal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBaktun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKatun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombeH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icH, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icTzol, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaHab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaTzol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtBaktun.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        verificarFecha();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBaktunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaktunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaktunActionPerformed

    private void verificarFecha() {
        if (boxDate.getDate() != null) {
            //fecha pivote
            String Dateinicio = "2001-01-01";
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date fechaInicio = date.parse(Dateinicio);
                long fechaFinalMs = fechaInicio.getTime();

                long fechaInicialMs = boxDate.getDate().getTime();

                long diferencia = fechaFinalMs - fechaInicialMs;

                double dias = Math.floor(diferencia / (1000 * 60 * 60 * 24));
                System.out.println(dias);
                int diasTranscurridos = 0;

                //si da negativo es porque paso del anio 2001
                if (dias < 0) {
                    diasTranscurridos = (int) (dias * (-1));
                    sobrePasaFechaPivote = true;
                } else {
                    diasTranscurridos = (int) (dias);
                    sobrePasaFechaPivote = false;
                }
                System.out.println("---------------------------- ");
                calculoRuedaCalendarica cRC = new calculoRuedaCalendarica();
                cRC.calculoCuentaLarga(diasTranscurridos, sobrePasaFechaPivote, txtBaktun, txtKatun, 
                        txtTun, txtUinal, txtKin);
                cRC.calculoTzolqin(diasTranscurridos, sobrePasaFechaPivote,icTzol, lblNombreT, diaTzol);
                cRC.calculoHaab(diasTranscurridos, sobrePasaFechaPivote, icH, lblNombeH, diaHab);

            } catch (ParseException ex) {
                Logger.getLogger(ruedaCalendarica.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar o ingresar una fecha");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser boxDate;
    private javax.swing.JTextField diaHab;
    private javax.swing.JTextField diaTzol;
    private javax.swing.JLabel icH;
    private javax.swing.JLabel icTzol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBaktun;
    private javax.swing.JLabel lblKatun;
    private javax.swing.JLabel lblKin;
    private javax.swing.JLabel lblNombeH;
    private javax.swing.JLabel lblNombreT;
    private javax.swing.JLabel lblTun;
    private javax.swing.JLabel lblUinal;
    private javax.swing.JTextField txtBaktun;
    private javax.swing.JTextField txtKatun;
    private javax.swing.JTextField txtKin;
    private javax.swing.JTextField txtTun;
    private javax.swing.JTextField txtUinal;
    // End of variables declaration//GEN-END:variables
}
